name: Quality

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  quality:
    name: Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v7

      - name: Install
        uses: ./.github/actions/install

      - name: Build packages
        run: bun run build

      - name: Install Playwright Browsers
        run: bunx playwright install --with-deps

      - name: Run tests
        run: bun test:e2e

      - name: Run lint
        run: bun lint
